name: create-issue

on:
  push:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Create issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python create-issue.py
