name: exit_test

on: workflow_dispatch

jobs:
  echo-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check 
      id: check
      run: |
        START_TEST="true"
        echo "::set-output name=START_TEST::$START_TEST"
    - name: echo hoge
      if: ${{ steps.check.outputs.START_TEST == 'true' }}
      run: echo hoge
    - name: echo fuga
      if: ${{ steps.check.outputs.START_TEST == 'true' }}
      run: echo fuga
