name: exit_test

on: workflow_dispatch

jobs:
  echo-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: exit
      run: exit 0
    - name: echo hoge
      run: echo hoge
