name: tag

on:
  push:
    branches:
    - master

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set new version
      run: echo "::set-env name=NEW_VERSION::$(grep versionName build.gradle | grep -o '".*"' | sed 's/"//g')"
    - name: Debug
      run: echo $NEW_VERSION
